name: Snowflake_Audit_DBT_Project_Cost
version: 1.0.0
config-version: 2
profile: Snowflake_Audit_DBT_Project_Cost
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  Snowflake_Audit_DBT_Project_Cost:
    +materialized: view
