version: 2

sources:
  - name: account_usage
    database: SNOWFLAKE
    schema: ACCOUNT_USAGE
    tables:
      - name: METERING_HISTORY
      - name: METERING_DAILY_HISTORY
      - name: WAREHOUSE_METERING_HISTORY

  - name: organization_usage
    database: SNOWFLAKE
    schema: ORGANIZATION_USAGE
    tables:
      - name: METERING_DAILY_HISTORY
      - name: USAGE_IN_CURRENCY_DAILY
      - name: WAREHOUSE_METERING_HISTORY
      - name: STAGE_STORAGE_USAGE_HISTORY
      - name: ACCOUNTS