version: 2

sources:
  - name: account_usage
    database: SNOWFLAKE
    schema: ACCOUNT_USAGE
    tables:
      - name: METERING_HISTORY
      - name: METERING_DAILY_HISTORY
      - name: WAREHOUSE_METERING_HISTORY

  - name: organization_usage
    database: SNOWFLAKE
    schema: ORGANIZATION_USAGE
    tables:
      - name: ACCOUNTS
      - name: AUTOMATIC_CLUSTERING_HISTORY
      - name: METERING_DAILY_HISTORY
      - name: MONETIZED_USAGE_DAILY
      - name: RATE_SHEET_DAILY
      - name: STAGE_STORAGE_USAGE_HISTORY
      - name: USAGE_IN_CURRENCY_DAILY
      - name: WAREHOUSE_METERING_HISTORY
      - name: STORAGE_DAILY_HISTORY
      - name: DATA_TRANSFER_HISTORY
      - name: DATABASE_STORAGE_USAGE_HISTORY